#!/usr/bin/env python3
"""
Project: FreeBASIC runtime
File: generate-ustring-case.py
Purpose: Generate the Unicode 17.0 default casing tables for USTRING.
Responsibilities: Combine simple/full mappings and merge casing properties.
This file intentionally does NOT contain locale tailoring or runtime decoding.

Usage: generate-ustring-case.py /path/to/Unicode-17.0.0-ucd
Input files are UnicodeData.txt, SpecialCasing.txt, DerivedCoreProperties.txt, and CaseFolding.txt
from https://www.unicode.org/Public/17.0.0/ucd/ . No network is needed at build time.
"""

import argparse
from pathlib import Path


def ranges(values):
    """Merge property intervals so the runtime can use binary search."""
    result = []
    for first, last in sorted(values):
        if result and first <= result[-1][1] + 1:
            result[-1] = (result[-1][0], max(last, result[-1][1]))
        else:
            result.append((first, last))
    return result


def generate(ucd, output):
    lower, upper, fold = {}, {}, {}
    for line in (ucd / "UnicodeData.txt").read_text().splitlines():
        fields = line.split(";")
        scalar = int(fields[0], 16)
        if fields[12]:
            upper[scalar] = [int(fields[12], 16)]
        if fields[13]:
            lower[scalar] = [int(fields[13], 16)]

    special = (ucd / "SpecialCasing.txt").read_text()
    properties = (ucd / "DerivedCoreProperties.txt").read_text()
    if "SpecialCasing-17.0.0.txt" not in special or "DerivedCoreProperties-17.0.0.txt" not in properties:
        raise ValueError("USTRING tables require Unicode 17.0.0 input files")
    for line in special.splitlines():
        fields = line.split("#", 1)[0].strip().split(";")
        if len(fields) < 5 or fields[4].strip():
            continue
        scalar = int(fields[0], 16)
        lower[scalar] = [int(value, 16) for value in fields[1].split()]
        upper[scalar] = [int(value, 16) for value in fields[3].split()]

    folding = (ucd / "CaseFolding.txt").read_text()
    if "CaseFolding-17.0.0.txt" not in folding:
        raise ValueError("Case folding requires Unicode 17.0.0 input")
    for line in folding.splitlines():
        fields = line.split("#", 1)[0].strip().split(";")
        if len(fields) >= 3 and fields[1].strip() in ("C", "F"):
            fold[int(fields[0], 16)] = [int(value, 16) for value in fields[2].split()]

    sets = {"Cased": [], "Case_Ignorable": []}
    for line in properties.splitlines():
        fields = line.split("#", 1)[0].strip().split(";")
        if len(fields) != 2 or fields[1].strip() not in sets:
            continue
        limits = [int(value, 16) for value in fields[0].strip().split("..")]
        sets[fields[1].strip()].append((limits[0], limits[-1]))

    text = ["/*", "    FreeBASIC Runtime Library", "    File: ustr_case_data.h", "    Purpose: Supply generated Unicode 17.0.0 default case mappings.", "    Responsibilities: Full upper/lower maps and final-sigma properties.", "    This file intentionally does NOT contain runtime algorithms.", "", "    Generated by build_scripts/generate-ustring-case.py. Do not edit.", "    Unicode data copyright Unicode, Inc. See inc/unicode-license.txt.", "*/", ""]
    for name, mapping in [("lower", lower), ("upper", upper), ("fold", fold)]:
        text.append(f"static const UTF8_CASE_MAP {name}_map[] = {{")
        for scalar, mapped in sorted(mapping.items()):
            if mapped == [scalar]:
                continue
            if not 1 <= len(mapped) <= 3:
                raise ValueError("Case mapping exceeds the runtime's three-scalar bound")
            padded = mapped + [0] * (3 - len(mapped))
            values = ", ".join(f"0x{value:X}" for value in padded)
            text.append(f"\t{{ 0x{scalar:X}, {len(mapped)}, {{ {values} }} }},")
        text.extend(["};", ""])
    for name, intervals in sets.items():
        text.append(f"static const UTF8_CASE_RANGE {name.lower()}_ranges[] = {{")
        for first, last in ranges(intervals):
            text.append(f"\t{{ 0x{first:X}, 0x{last:X} }},")
        text.extend(["};", ""])
    text.append("/* end of ustr_case_data.h */")
    output.write_text("\n".join(text) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ucd", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "src/rtlib/ustr_case_data.h")
    args = parser.parse_args()
    generate(args.ucd, args.output)

# end of generate-ustring-case.py
