typedef   signed char       int8;
typedef unsigned char      uint8;
typedef   signed short      int16;
typedef unsigned short     uint16;
typedef   signed int        int32;
typedef unsigned int       uint32;
typedef   signed long long  int64;
typedef unsigned long long uint64;
typedef struct { char *data; int32 len; int32 size; } FBSTRING;
typedef int8 boolean;
struct $16__FB_ARRAYDIMTB$ {
	int32 ELEMENTS;
	int32 LBOUND;
	int32 UBOUND;
};
#define __FB_STATIC_ASSERT( expr ) extern int __$fb_structsizecheck[(expr) ? 1 : -1]
__FB_STATIC_ASSERT( sizeof( struct $16__FB_ARRAYDIMTB$ ) == 12 );
struct $7FBARRAYIvE {
	void* DATA;
	void* PTR;
	int32 SIZE;
	int32 ELEMENT_LEN;
	int32 DIMENSIONS;
	int32 FLAGS;
	struct $16__FB_ARRAYDIMTB$ DIMTB[8];
};
__FB_STATIC_ASSERT( sizeof( struct $7FBARRAYIvE ) == 120 );
int32 fb_ArrayRedimEx( struct $7FBARRAYIvE*, const uint32, const int32, const int32, const uint32, ... );
int32 fb_ArrayErase( struct $7FBARRAYIvE* );
struct $7FBARRAYIKvE {
	void* DATA;
	void* PTR;
	int32 SIZE;
	int32 ELEMENT_LEN;
	int32 DIMENSIONS;
	int32 FLAGS;
	struct $16__FB_ARRAYDIMTB$ DIMTB[8];
};
__FB_STATIC_ASSERT( sizeof( struct $7FBARRAYIKvE ) == 120 );
int32 fb_ArrayLBound( struct $7FBARRAYIKvE*, const int32 );
int32 fb_ArrayUBound( struct $7FBARRAYIKvE*, const int32 );
int32 fb_Width( const int32, const int32 );
int32 fb_Locate( const int32, const int32, const int32, const int32, const int32 );
int32 fb_Pos( const int32 );
int32 fb_GetY( void );
void fb_Cls( const int32 );
uint32 fb_Color( const int32, const int32, const uint32 );
FBSTRING* fb_Inkey( void );
void fb_DataRestore( void* );
void fb_DataReadStr( void*, const int32, const int32 );
void fb_DataReadInt( int32* );
void fb_DataReadLongint( int64* );
void fb_DataReadDouble( double* );
int32 fb_ErrorGetNum( void );
int32 fb_FileOpen( const FBSTRING*, const uint32, const uint32, const uint32, const int32, const int32 );
int32 fb_FileClose( const int32 );
int32 fb_FilePut( const int32, const int32, const void*, const uint32 );
int32 fb_FilePutStr( const int32, const int32, const void*, const int32 );
int32 fb_FileGet( const int32, const int32, void*, const uint32 );
int32 fb_FileGetStr( const int32, const int32, void*, const int32 );
int64 fb_FileTell( const int32 );
int32 fb_FileSeek( const int32, const int32 );
FBSTRING* fb_FileStrInput( const int32, const int32 );
int32 fb_FileLineInput( const int32, void*, const int32, const int32 );
int32 fb_LineInput( const FBSTRING*, void*, const int32, const int32, const int32, const int32 );
int32 fb_FileInput( const int32 );
int32 fb_ConsoleInput( const FBSTRING*, const int32, const int32 );
int32 fb_InputBool( boolean* );
int32 fb_InputByte( int8* );
int32 fb_InputUbyte( uint8* );
int32 fb_InputShort( int16* );
int32 fb_InputUshort( uint16* );
int32 fb_InputInt( int32* );
int32 fb_InputUint( uint32* );
int32 fb_InputLongint( int64* );
int32 fb_InputUlongint( uint64* );
int32 fb_InputSingle( float* );
int32 fb_InputDouble( double* );
int32 fb_InputString( void*, const int32, const int32 );
int32 fb_FileLock( const int32, const uint32, const uint32 );
int32 fb_FileUnlock( const int32, const uint32, const uint32 );
int32 rename( const char*, const char* );
int32 fb_FileFree( void );
int32 fb_FileEof( const int32 );
int32 fb_FileKill( const FBSTRING* );
void fb_FileReset( void );
int64 fb_FileSize( const int32 );
int64 fb_FileLocation( const int32 );
void fb_Randomize( double, int32 );
double fb_Rnd( float );
double fb_FIXDouble( double );
void* malloc( uint32 );
void* calloc( uint32, uint32 );
void* realloc( void*, uint32 );
void free( void* );
void fb_PrintBool( const int32, const boolean, const int32 );
void fb_PrintByte( const int32, const int8, const int32 );
void fb_PrintUByte( const int32, const uint8, const int32 );
void fb_PrintShort( const int32, const int16, const int32 );
void fb_PrintUShort( const int32, const uint16, const int32 );
void fb_PrintInt( const int32, const int32, const int32 );
void fb_PrintUInt( const int32, const uint32, const int32 );
void fb_PrintLongint( const int32, const int64, const int32 );
void fb_PrintULongint( const int32, const uint64, const int32 );
void fb_PrintDouble( const int32, const double, const int32 );
void fb_PrintString( const int32, const FBSTRING*, const int32 );
void fb_PrintSPC( const int32, const int32 );
void fb_PrintTab( const int32, const int32 );
void fb_WriteBool( const int32, const boolean, const int32 );
void fb_WriteByte( const int32, const int8, const int32 );
void fb_WriteUByte( const int32, const uint8, const int32 );
void fb_WriteShort( const int32, const int16, const int32 );
void fb_WriteUShort( const int32, const uint16, const int32 );
void fb_WriteInt( const int32, const int32, const int32 );
void fb_WriteUInt( const int32, const uint32, const int32 );
void fb_WriteLongint( const int32, const int64, const int32 );
void fb_WriteULongint( const int32, const uint64, const int32 );
void fb_WriteSingle( const int32, const float, const int32 );
void fb_WriteDouble( const int32, const double, const int32 );
void fb_WriteString( const int32, const FBSTRING*, const int32 );
int32 fb_PrintUsingInit( const FBSTRING* );
int32 fb_PrintUsingStr( const int32, const FBSTRING*, const int32 );
int32 fb_PrintUsingDouble( const int32, const double, const int32 );
int32 fb_PrintUsingLongint( const int32, const int64, const int32 );
int32 fb_PrintUsingEnd( const int32 );
FBSTRING* fb_StrInit( void*, const int32, const void*, const int32, const int32 );
FBSTRING* fb_StrAssign( void*, const int32, const void*, const int32, const int32 );
int32 fb_hStrDelTemp( const FBSTRING* );
int32 fb_StrCompare( const void*, const int32, const void*, const int32 );
FBSTRING* fb_StrConcatAssign( void*, const int32, const void*, const int32, const int32 );
FBSTRING* fb_StrAllocTempDescF( const void*, const int32 );
FBSTRING* fb_StrAllocTempDescZEx( const char*, const int32 );
FBSTRING* fb_StrMid( const FBSTRING*, const int32, const int32 );
void fb_StrAssignMid( FBSTRING*, const int32, const int32, const FBSTRING* );
FBSTRING* fb_StrFill1( const int32, const int32 );
int32 fb_StrLen( const void*, const int32 );
void fb_StrLsetANA( void*, const int32, const FBSTRING* );
void fb_StrRsetANA( void*, const int32, const FBSTRING* );
uint32 fb_ASC( const FBSTRING*, const int32 );
int32 fb_StrInstr( const int32, const FBSTRING*, const FBSTRING* );
int32 fb_StrInstrRev( const FBSTRING*, const FBSTRING*, const int32 );
FBSTRING* fb_TRIM( const FBSTRING* );
FBSTRING* fb_RTRIM( const FBSTRING* );
FBSTRING* fb_LTRIM( const FBSTRING* );
double fb_VAL( const FBSTRING* );
int32 fb_VALINT( const FBSTRING* );
uint32 fb_VALUINT( const FBSTRING* );
int64 fb_VALLNG( const FBSTRING* );
uint64 fb_VALULNG( const FBSTRING* );
FBSTRING* fb_HEX_b( const uint8 );
FBSTRING* fb_HEX_i( const uint32 );
FBSTRING* fb_OCT_i( const uint32 );
FBSTRING* fb_BIN_i( const uint32 );
FBSTRING* fb_MKD( const double );
FBSTRING* fb_MKS( const float );
FBSTRING* fb_MKI( const int32 );
FBSTRING* fb_MKL( const int32 );
FBSTRING* fb_LEFT( const FBSTRING*, const int32 );
FBSTRING* fb_RIGHT( const FBSTRING*, const int32 );
FBSTRING* fb_SPACE( const int32 );
FBSTRING* fb_StrLcase2( const FBSTRING*, const int32 );
FBSTRING* fb_StrUcase2( const FBSTRING*, const int32 );
double fb_CVD( const FBSTRING* );
float fb_CVS( const FBSTRING* );
int32 fb_CVL( const FBSTRING* );
void fb_End( const int32 );
FBSTRING* fb_Command( const int32 );
FBSTRING* fb_CurDir( void );
FBSTRING* fb_ExePath( void );
double fb_Timer( void );
FBSTRING* fb_Time( void );
FBSTRING* fb_Date( void );
int32 fb_Shell( const FBSTRING* );
FBSTRING* fb_GetEnviron( const FBSTRING* );
int32 fb_SleepEx( const int32, const int32 );
FBSTRING* fb_DirNext( int32* );
FBSTRING* fb_Dir( const FBSTRING*, const int32, int32* );
int32 fb_MkDir( const FBSTRING* );
int32 fb_RmDir( const FBSTRING* );
int32 fb_ChDir( const FBSTRING* );
static void fb_ctor__fbhello_smoke( void ) __attribute__(( constructor ));
struct $10SAMPLE_REC {
	int32 N;
	uint8 TEXT[6];
};
__FB_STATIC_ASSERT( sizeof( struct $10SAMPLE_REC ) == 12 );
static void _ZN10SAMPLE_RECC1Ev( struct $10SAMPLE_REC* );
static int32 GOSUB_TOTAL$;
struct $14__FB_DATADESC$ {
	int16 TYPE __attribute__((packed, aligned(1)));
	void* NODE __attribute__((packed, aligned(1)));
};
__FB_STATIC_ASSERT( sizeof( struct $14__FB_DATADESC$ ) == 6 );
static struct $14__FB_DATADESC$ label$5[4] = { { (int16)11, (void*)"stored text" }, { (int16)4, (void*)"6.25" }, { (int16)13, (void*)"1234567890123" }, { (int16)-1, (void*)0u } };
static struct $14__FB_DATADESC$ label$3[3] = { { (int16)2, (void*)"10" }, { (int16)2, (void*)"20" }, { (int16)-1, (void*)label$5 } };
