/*
    FreeBASIC AmigaOS test transport
    --------------------------------

    File: guest-runner.c

    Purpose:
        Execute staged Hunk programs and preserve their native return codes.

    Responsibilities:
        - read a bounded tab-separated job manifest through dos.library
        - set each program's directory, name, module, arguments, and output
        - restore the controller's process state and release loaded segments
        - emit progress and completion records directly to the host volume

    This file intentionally does NOT contain:
        - FreeBASIC runtime initialization or test expectation policy
        - shell emulation, standard C streams, or SDK allocator dependencies

    Manifest layout, one job per line:
        identifier TAB executable TAB directory TAB arguments TAB expected-code

    The controller uses the ROM DOS API. RunCommand borrows the current
    process, so directory locks and CLI module ownership must be restored
    after every child. A completed record proves that the child returned to
    the controller; printed child output alone is insufficient evidence.
*/

#include <proto/exec.h>
#include <proto/dos.h>
#include <dos/dosextens.h>

#define FB_AMIGA_LINE_BYTES 8192
#define FB_AMIGA_PATH_BYTES 1024
#define FB_AMIGA_CHILD_STACK (1024UL * 1024UL)

struct ExecBase *SysBase;
struct DosLibrary *DOSBase;

static char manifest_line[FB_AMIGA_LINE_BYTES];
static char input_buffer[4096];
static LONG input_position;
static LONG input_length;

static ULONG text_length(const char *text)
{
    ULONG length = 0;
    while (text[length] != '\0') ++length;
    return length;
}

static void write_text(BPTR file, const char *text)
{
    ULONG remaining = text_length(text);
    while (remaining != 0) {
        LONG written = Write(file, (APTR)text, (LONG)remaining);
        if (written <= 0) return;
        text += written;
        remaining -= (ULONG)written;
    }
}

static void write_number(BPTR file, LONG value)
{
    char buffer[16];
    int index = (int)sizeof(buffer) - 1;
    ULONG magnitude = value < 0 ? 0UL - (ULONG)value : (ULONG)value;

    buffer[index] = '\0';
    do {
        buffer[--index] = (char)('0' + magnitude % 10);
        magnitude /= 10;
    } while (magnitude != 0);
    if (value < 0) buffer[--index] = '-';
    write_text(file, buffer + index);
}

static int read_line(BPTR input)
{
    ULONG length = 0;

    while (TRUE) {
        char character;
        if (input_position == input_length) {
            input_length = Read(input, input_buffer, sizeof(input_buffer));
            input_position = 0;
            if (input_length < 0) return -1;
            if (input_length == 0) {
                manifest_line[length] = '\0';
                return length == 0 ? 0 : 1;
            }
        }
        character = input_buffer[input_position++];
        if (character == '\r') continue;
        if (character == '\n') { manifest_line[length] = '\0'; return 1; }
        if (character == '\0' || length >= sizeof(manifest_line) - 2)
            return -1;
        manifest_line[length++] = character;
    }
}

static void assign_directory(const char *name, const char *path)
{
    BPTR lock = Lock(path, SHARED_LOCK);
    if (lock != 0 && !AssignLock(name, lock)) UnLock(lock);
}

static LONG run_job(char **fields, BPTR report)
{
    struct CommandLineInterface *cli = Cli();
    BPTR directory, previous_directory, program_directory;
    BPTR previous_program_directory, previous_output, segment;
    BPTR output, previous_module = 0;
    char previous_name[FB_AMIGA_PATH_BYTES];
    char log_path[FB_AMIGA_PATH_BYTES];
    char *cursor;
    ULONG length;
    LONG result;

    length = text_length(fields[0]);
    if (length == 0 || length > sizeof(log_path) - 20) return -1;
    /* IDs are generated by the host, but validate before constructing a path. */
    for (cursor = fields[0]; *cursor != '\0'; ++cursor)
        if (*cursor < '0' || *cursor > '9') return -1;
    cursor = log_path;
    {
        const char *prefix = "SYS:results/";
        const char *identifier = fields[0];
        while (*prefix) *cursor++ = *prefix++;
        while (*identifier) *cursor++ = *identifier++;
        *cursor++ = '.'; *cursor++ = 'l'; *cursor++ = 'o'; *cursor++ = 'g';
        *cursor = '\0';
    }
    output = Open(log_path, MODE_NEWFILE);
    if (output == 0) return -1;
    directory = Lock(fields[2], SHARED_LOCK);
    if (directory == 0) { Close(output); return -1; }
    previous_directory = CurrentDir(directory);
    program_directory = DupLock(directory);
    previous_program_directory = SetProgramDir(program_directory);
    if (!GetProgramName(previous_name, sizeof(previous_name))) previous_name[0] = '\0';
    SetProgramName(fields[1]);
    segment = LoadSeg(fields[1]);
    if (segment == 0) result = -1;
    else {
        if (cli != NULL) {
            previous_module = cli->cli_Module;
            cli->cli_Module = segment;
        }
        previous_output = SelectOutput(output);
        /* RunCommand's argument parser requires a final newline. The manifest
           has spare bytes at its end for this terminator and a trailing NUL. */
        length = text_length(fields[3]);
        fields[3][length] = '\n';
        fields[3][length + 1] = '\0';
        result = RunCommand(segment, FB_AMIGA_CHILD_STACK, fields[3], length + 1);
        SelectOutput(previous_output);
        if (cli != NULL) cli->cli_Module = previous_module;
        UnLoadSeg(segment);
    }
    SetProgramName(previous_name);
    program_directory = SetProgramDir(previous_program_directory);
    if (program_directory != 0) UnLock(program_directory);
    directory = CurrentDir(previous_directory);
    if (directory != 0) UnLock(directory);
    Close(output);
    write_text(report, "DONE\t"); write_text(report, fields[0]);
    write_text(report, "\t"); write_number(report, result);
    write_text(report, "\n"); Flush(report);
    return result;
}

LONG fb_amigaGuestMain(void)
{
    BPTR input, report;
    int status;

    /* Exec's base pointer is the documented longword at address four. */
    SysBase = *(struct ExecBase **)4;
    DOSBase = (struct DosLibrary *)OpenLibrary("dos.library", 37);
    if (DOSBase == NULL) return 20;
    assign_directory("T", "SYS:T");
    assign_directory("ENV", "SYS:ENV");
    input = Open("SYS:jobs.tsv", MODE_OLDFILE);
    report = Open("SYS:guest-results.tsv", MODE_NEWFILE);
    if (input == 0 || report == 0) {
        if (input != 0) Close(input);
        if (report != 0) Close(report);
        CloseLibrary((struct Library *)DOSBase);
        return 20;
    }
    write_text(report, "BOOT\n"); Flush(report);
    while ((status = read_line(input)) > 0) {
        char *fields[5];
        char *cursor = manifest_line;
        int count = 1;
        fields[0] = cursor;
        while (*cursor != '\0') {
            if (*cursor == '\t') {
                if (count == 5) { status = -1; break; }
                *cursor = '\0';
                fields[count++] = cursor + 1;
            }
            ++cursor;
        }
        if (status < 0 || count != 5) { status = -1; break; }
        write_text(report, "BEGIN\t"); write_text(report, fields[0]);
        write_text(report, "\n"); Flush(report);
        run_job(fields, report);
    }
    write_text(report, status < 0 ? "INVALID\n" : "COMPLETE\n");
    Close(input);
    Close(report);
    CloseLibrary((struct Library *)DOSBase);
    return status < 0 ? 20 : 0;
}

/* end of guest-runner.c */
