typedef   signed char       int8;
typedef unsigned char      uint8;
typedef   signed short      int16;
typedef unsigned short     uint16;
typedef   signed int        int32;
typedef unsigned int       uint32;
typedef   signed long long  int64;
typedef unsigned long long uint64;
typedef struct { char *data; int32 len; int32 size; } FBSTRING;
typedef int8 boolean;
typedef void (*tmp$5)( void );
typedef int32 (*tmp$4)( void );
int32 fb_FileOpen( const FBSTRING*, const uint32, const uint32, const uint32, const int32, const int32 );
int32 fb_FileOpenEncod( const FBSTRING*, const uint32, const uint32, const uint32, const int32, const int32, const char* );
int32 fb_FileClose( const int32 );
int32 fb_FilePut( const int32, const int32, const void*, const uint32 );
int32 fb_FileGet( const int32, const int32, void*, const uint32 );
int32 fb_FileLineInput( const int32, void*, const int32, const int32 );
int32 fb_FileLineInputWstr( const int32, uint32*, const int32 );
int32 fb_FileInput( const int32 );
int32 fb_InputBool( boolean* );
int32 fb_FileFree( void );
int32 fb_FileKill( const FBSTRING* );
void fb_PrintBool( const int32, const boolean, const int32 );
void fb_PrintInt( const int32, const int32, const int32 );
void fb_WriteBool( const int32, const boolean, const int32 );
FBSTRING* fb_StrAssign( void*, const int32, const void*, const int32, const int32 );
void fb_StrDelete( const FBSTRING* );
void fb_WstrDelete( const uint32* );
FBSTRING* fb_StrConcat( FBSTRING*, const void*, const int32, const void*, const int32 );
int32 fb_StrCompare( const void*, const int32, const void*, const int32 );
int32 fb_WstrCompare( const uint32*, const uint32* );
FBSTRING* fb_StrAllocTempDescZEx( const char*, const int32 );
uint32* fb_StrToWstr( const char* );
FBSTRING* fb_SPACE( const int32 );
static void fb_ctor__boolean_file( void ) __attribute__(( constructor ));
void _ZN4FBCU9ADD_SUITEEPcPFivES2_( char*, tmp$4, tmp$4 );
void _ZN4FBCU8ADD_TESTEPcS0_PFvvEb( char*, char*, tmp$5, boolean );
void _ZN4FBCU10CU_ASSERT_EbPciS0_S0_( boolean, char*, int32, char*, char* );
void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE13IO_TEST_ASCIIEv( void );
static void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE18IO_TEST_ASCII_CTOREv( void ) __attribute__(( constructor ));
void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE15IO_TEST_UTF16LEEv( void );
static void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE20IO_TEST_UTF16LE_CTOREv( void ) __attribute__(( constructor ));
void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE14IO_TEST_BINARYEv( void );
static void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE19IO_TEST_BINARY_CTOREv( void ) __attribute__(( constructor ));
static void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE13SUITE_CTOR166Ev( void ) __attribute__(( constructor ));

void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE13IO_TEST_ASCIIEv( void )
{
	_unusedlabel: ; void *_llvmbug18658 = &&_unusedlabel;
	int32 TMP$26$1;
	int32 TMP$27$1;
	int32 TMP$28$1;
	FBSTRING TMP$36$1;
	FBSTRING TMP$37$1;
	FBSTRING TMP$38$1;
	FBSTRING TMP$39$1;
	FBSTRING TMP$40$1;
	FBSTRING TMP$41$1;
	label$2:;
	int32 H$1;
	int32 vr$0 = fb_FileFree(  );
	H$1 = vr$0;
	boolean B$1;
	__builtin_memset( &B$1, 0, 1 );
	boolean F$1;
	F$1 = (boolean)0;
	boolean T$1;
	T$1 = (boolean)1;
	FBSTRING X$1;
	__builtin_memset( &X$1, 0, 12 );
	FBSTRING* vr$3 = fb_StrAllocTempDescZEx( (char*)"boolean/data-ascii.txt", 22 );
	fb_FileOpen( (FBSTRING*)vr$3, 2u, 0u, 0u, H$1, 0 );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 29, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 30, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 31, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 32, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 34, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 35, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 36, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 37, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 39, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 40, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 41, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 42, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileClose( H$1 );
	FBSTRING* vr$52 = fb_StrAllocTempDescZEx( (char*)"boolean/data-ascii-test.txt", 27 );
	fb_FileOpen( (FBSTRING*)vr$52, 3u, 0u, 0u, H$1, 0 );
	TMP$26$1 = H$1;
	fb_WriteBool( TMP$26$1, (boolean)0, 2 );
	fb_WriteBool( TMP$26$1, (boolean)1, 2 );
	fb_WriteBool( TMP$26$1, F$1, 2 );
	fb_WriteBool( TMP$26$1, T$1, 1 );
	TMP$27$1 = H$1;
	fb_PrintBool( TMP$27$1, (boolean)0, 2 );
	fb_PrintBool( TMP$27$1, (boolean)1, 2 );
	fb_PrintBool( TMP$27$1, F$1, 2 );
	fb_PrintBool( TMP$27$1, T$1, 1 );
	TMP$28$1 = H$1;
	fb_PrintInt( TMP$28$1, 0, 2 );
	fb_PrintInt( TMP$28$1, 0, 2 );
	fb_PrintInt( TMP$28$1, 0, 2 );
	fb_PrintInt( TMP$28$1, 0, 1 );
	fb_FileClose( H$1 );
	FBSTRING* vr$53 = fb_StrAllocTempDescZEx( (char*)"boolean/data-ascii-test.txt", 27 );
	fb_FileOpen( (FBSTRING*)vr$53, 2u, 0u, 0u, H$1, 0 );
	fb_FileLineInput( H$1, (void*)&X$1, -1, 0 );
	int32 vr$56 = fb_StrCompare( (void*)&X$1, -1, (void*)"false,true,false,true", 22 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(vr$56 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 54, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(x,\x22" "false,true,false,true\x22)" );
	fb_FileLineInput( H$1, (void*)&X$1, -1, 0 );
	FBSTRING* vr$60 = fb_SPACE( 9 );
	FBSTRING* vr$61 = fb_SPACE( 10 );
	FBSTRING* vr$62 = fb_SPACE( 9 );
	__builtin_memset( &TMP$36$1, 0, 12 );
	FBSTRING* vr$65 = fb_StrConcat( &TMP$36$1, (void*)"false", 6, (void*)vr$62, -1 );
	__builtin_memset( &TMP$37$1, 0, 12 );
	FBSTRING* vr$68 = fb_StrConcat( &TMP$37$1, (void*)vr$65, -1, (void*)"true", 5 );
	__builtin_memset( &TMP$38$1, 0, 12 );
	FBSTRING* vr$71 = fb_StrConcat( &TMP$38$1, (void*)vr$68, -1, (void*)vr$61, -1 );
	__builtin_memset( &TMP$39$1, 0, 12 );
	FBSTRING* vr$74 = fb_StrConcat( &TMP$39$1, (void*)vr$71, -1, (void*)"false", 6 );
	__builtin_memset( &TMP$40$1, 0, 12 );
	FBSTRING* vr$77 = fb_StrConcat( &TMP$40$1, (void*)vr$74, -1, (void*)vr$60, -1 );
	__builtin_memset( &TMP$41$1, 0, 12 );
	FBSTRING* vr$80 = fb_StrConcat( &TMP$41$1, (void*)vr$77, -1, (void*)"true", 5 );
	int32 vr$82 = fb_StrCompare( (void*)&X$1, -1, (void*)vr$80, -1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(vr$82 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 56, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(x,\x22" "false\x22+space(9)+\x22true\x22+space(10)+\x22" "false\x22+space(9)+\x22true\x22)" );
	fb_FileClose( H$1 );
	FBSTRING* vr$85 = fb_StrAllocTempDescZEx( (char*)"boolean/data-ascii-test.txt", 27 );
	fb_FileOpen( (FBSTRING*)vr$85, 2u, 0u, 0u, H$1, 0 );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 60, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 61, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 62, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 63, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_ASCII", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileClose( H$1 );
	FBSTRING* vr$102 = fb_StrAllocTempDescZEx( (char*)"boolean/data-ascii-test.txt", 27 );
	fb_FileKill( (FBSTRING*)vr$102 );
	fb_StrDelete( (FBSTRING*)&X$1 );
	label$3:;
}

void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE15IO_TEST_UTF16LEEv( void )
{
	_unusedlabel: ; void *_llvmbug18658 = &&_unusedlabel;
	int32 TMP$51$1;
	int32 TMP$52$1;
	int32 TMP$53$1;
	FBSTRING TMP$59$1;
	FBSTRING TMP$60$1;
	FBSTRING TMP$61$1;
	FBSTRING TMP$62$1;
	FBSTRING TMP$63$1;
	FBSTRING TMP$64$1;
	FBSTRING TMP$65$1;
	uint32* TMP$66$1;
	label$6:;
	int32 H$1;
	int32 vr$0 = fb_FileFree(  );
	H$1 = vr$0;
	boolean B$1;
	__builtin_memset( &B$1, 0, 1 );
	boolean F$1;
	F$1 = (boolean)0;
	boolean T$1;
	T$1 = (boolean)1;
	uint32 X$1[80];
	__builtin_memset( (uint32*)X$1, 0, 320 );
	FBSTRING* vr$3 = fb_StrAllocTempDescZEx( (char*)"boolean/data-utf16le.txt", 24 );
	fb_FileOpenEncod( (FBSTRING*)vr$3, 2u, 0u, 0u, H$1, 0, (char*)"utf16" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 79, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 80, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 81, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 82, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 84, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 85, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 86, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 87, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 89, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 90, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 91, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 92, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileClose( H$1 );
	FBSTRING* vr$52 = fb_StrAllocTempDescZEx( (char*)"boolean/data-utf16le-test.txt", 29 );
	fb_FileOpenEncod( (FBSTRING*)vr$52, 3u, 0u, 0u, H$1, 0, (char*)"utf16" );
	TMP$51$1 = H$1;
	fb_WriteBool( TMP$51$1, (boolean)0, 2 );
	fb_WriteBool( TMP$51$1, (boolean)1, 2 );
	fb_WriteBool( TMP$51$1, F$1, 2 );
	fb_WriteBool( TMP$51$1, T$1, 1 );
	TMP$52$1 = H$1;
	fb_PrintBool( TMP$52$1, (boolean)0, 2 );
	fb_PrintBool( TMP$52$1, (boolean)1, 2 );
	fb_PrintBool( TMP$52$1, F$1, 2 );
	fb_PrintBool( TMP$52$1, T$1, 1 );
	TMP$53$1 = H$1;
	fb_PrintInt( TMP$53$1, 0, 2 );
	fb_PrintInt( TMP$53$1, 0, 2 );
	fb_PrintInt( TMP$53$1, 0, 2 );
	fb_PrintInt( TMP$53$1, 0, 1 );
	fb_FileClose( H$1 );
	FBSTRING* vr$53 = fb_StrAllocTempDescZEx( (char*)"boolean/data-utf16le-test.txt", 29 );
	fb_FileOpenEncod( (FBSTRING*)vr$53, 2u, 0u, 0u, H$1, 0, (char*)"utf16" );
	fb_FileLineInputWstr( H$1, (uint32*)X$1, 80 );
	int32 vr$56 = fb_WstrCompare( (uint32*)X$1, (uint32*)L"false,true,false,true" );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(vr$56 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 104, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(x,wstr(\x22" "false,true,false,true\x22))" );
	fb_FileLineInputWstr( H$1, (uint32*)X$1, 80 );
	__builtin_memset( &TMP$65$1, 0, 12 );
	FBSTRING* vr$61 = fb_SPACE( 9 );
	FBSTRING* vr$62 = fb_SPACE( 10 );
	FBSTRING* vr$63 = fb_SPACE( 9 );
	__builtin_memset( &TMP$59$1, 0, 12 );
	FBSTRING* vr$66 = fb_StrConcat( &TMP$59$1, (void*)"false", 6, (void*)vr$63, -1 );
	__builtin_memset( &TMP$60$1, 0, 12 );
	FBSTRING* vr$69 = fb_StrConcat( &TMP$60$1, (void*)vr$66, -1, (void*)"true", 5 );
	__builtin_memset( &TMP$61$1, 0, 12 );
	FBSTRING* vr$72 = fb_StrConcat( &TMP$61$1, (void*)vr$69, -1, (void*)vr$62, -1 );
	__builtin_memset( &TMP$62$1, 0, 12 );
	FBSTRING* vr$75 = fb_StrConcat( &TMP$62$1, (void*)vr$72, -1, (void*)"false", 6 );
	__builtin_memset( &TMP$63$1, 0, 12 );
	FBSTRING* vr$78 = fb_StrConcat( &TMP$63$1, (void*)vr$75, -1, (void*)vr$61, -1 );
	__builtin_memset( &TMP$64$1, 0, 12 );
	FBSTRING* vr$81 = fb_StrConcat( &TMP$64$1, (void*)vr$78, -1, (void*)"true", 5 );
	fb_StrAssign( (void*)&TMP$65$1, -1, (void*)vr$81, -1, 0 );
	uint32* vr$83 = fb_StrToWstr( (char*)*(char**)&TMP$65$1 );
	TMP$66$1 = vr$83;
	int32 vr$85 = fb_WstrCompare( (uint32*)X$1, (uint32*)TMP$66$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(vr$85 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 106, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(x,wstr(\x22" "false\x22+space(9)+\x22true\x22+space(10)+\x22" "false\x22+space(9)+\x22true\x22))" );
	fb_WstrDelete( (uint32*)TMP$66$1 );
	fb_StrDelete( (FBSTRING*)&TMP$65$1 );
	fb_FileClose( H$1 );
	FBSTRING* vr$89 = fb_StrAllocTempDescZEx( (char*)"boolean/data-utf16le-test.txt", 29 );
	fb_FileOpenEncod( (FBSTRING*)vr$89, 2u, 0u, 0u, H$1, 0, (char*)"utf16" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 110, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 111, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 112, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileInput( H$1 );
	fb_InputBool( &B$1 );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 113, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_UTF16LE", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileClose( H$1 );
	FBSTRING* vr$106 = fb_StrAllocTempDescZEx( (char*)"boolean/data-utf16le-test.txt", 29 );
	fb_FileKill( (FBSTRING*)vr$106 );
	label$7:;
}

void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE14IO_TEST_BINARYEv( void )
{
	_unusedlabel: ; void *_llvmbug18658 = &&_unusedlabel;
	label$10:;
	int32 H$1;
	int32 vr$0 = fb_FileFree(  );
	H$1 = vr$0;
	boolean B$1;
	__builtin_memset( &B$1, 0, 1 );
	int8 C$1;
	__builtin_memset( &C$1, 0, 1 );
	boolean F$1;
	F$1 = (boolean)0;
	boolean T$1;
	T$1 = (boolean)1;
	uint32 X$1[80];
	__builtin_memset( (uint32*)X$1, 0, 320 );
	FBSTRING* vr$4 = fb_StrAllocTempDescZEx( (char*)"boolean/data-binary-test.dat", 28 );
	fb_FileOpen( (FBSTRING*)vr$4, 3u, 0u, 0u, H$1, 0 );
	fb_FileClose( H$1 );
	FBSTRING* vr$5 = fb_StrAllocTempDescZEx( (char*)"boolean/data-binary-test.dat", 28 );
	fb_FileOpen( (FBSTRING*)vr$5, 0u, 0u, 0u, H$1, 0 );
	B$1 = (boolean)0;
	fb_FilePut( H$1, 0, (void*)&B$1, 1u );
	B$1 = (boolean)1;
	fb_FilePut( H$1, 0, (void*)&B$1, 1u );
	B$1 = (boolean)0;
	fb_FilePut( H$1, 0, (void*)&B$1, 1u );
	B$1 = (boolean)1;
	fb_FilePut( H$1, 0, (void*)&B$1, 1u );
	C$1 = (int8)0;
	fb_FilePut( H$1, 0, (void*)&C$1, 1u );
	C$1 = (int8)1;
	fb_FilePut( H$1, 0, (void*)&C$1, 1u );
	C$1 = (int8)0;
	fb_FilePut( H$1, 0, (void*)&C$1, 1u );
	C$1 = (int8)1;
	fb_FilePut( H$1, 0, (void*)&C$1, 1u );
	B$1 = (boolean)0;
	fb_FilePut( H$1, 0, (void*)&B$1, 1u );
	B$1 = (boolean)1;
	fb_FilePut( H$1, 0, (void*)&B$1, 1u );
	B$1 = (boolean)0;
	fb_FilePut( H$1, 0, (void*)&B$1, 1u );
	B$1 = (boolean)1;
	fb_FilePut( H$1, 0, (void*)&B$1, 1u );
	fb_FileClose( H$1 );
	FBSTRING* vr$18 = fb_StrAllocTempDescZEx( (char*)"boolean/data-binary-test.dat", 28 );
	fb_FileOpen( (FBSTRING*)vr$18, 0u, 0u, 0u, H$1, 0 );
	fb_FileGet( H$1, 0, (void*)&B$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 148, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileGet( H$1, 0, (void*)&B$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 149, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileGet( H$1, 0, (void*)&B$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 150, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileGet( H$1, 0, (void*)&B$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 151, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileGet( H$1, 0, (void*)&B$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 152, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileGet( H$1, 0, (void*)&B$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 153, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileGet( H$1, 0, (void*)&B$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 154, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(b,0)" );
	fb_FileGet( H$1, 0, (void*)&B$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-(-B$1 == -1) != 0), (char*)"tests/boolean/boolean_file.bas", 155, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(b,(-1))" );
	fb_FileGet( H$1, 0, (void*)&C$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-((int32)C$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 156, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(c,0)" );
	fb_FileGet( H$1, 0, (void*)&C$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-((int32)C$1 == 1) != 0), (char*)"tests/boolean/boolean_file.bas", 157, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(c,1)" );
	fb_FileGet( H$1, 0, (void*)&C$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-((int32)C$1 == 0) != 0), (char*)"tests/boolean/boolean_file.bas", 158, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(c,0)" );
	fb_FileGet( H$1, 0, (void*)&C$1, 1u );
	_ZN4FBCU10CU_ASSERT_EbPciS0_S0_( (boolean)(-((int32)C$1 == 1) != 0), (char*)"tests/boolean/boolean_file.bas", 159, (char*)"TESTS.FBC_TESTS.BOOLEAN_.BOOLEAN_FILE.IO_TEST_BINARY", (char*)"CU_ASSERT_EQUAL(c,1)" );
	fb_FileClose( H$1 );
	FBSTRING* vr$67 = fb_StrAllocTempDescZEx( (char*)"boolean/data-binary-test.dat", 28 );
	fb_FileKill( (FBSTRING*)vr$67 );
	label$11:;
}

__attribute__(( constructor )) static void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE18IO_TEST_ASCII_CTOREv( void )
{
	_unusedlabel: ; void *_llvmbug18658 = &&_unusedlabel;
	label$4:;
	_ZN4FBCU8ADD_TESTEPcS0_PFvvEb( (char*)"fbc_tests.boolean_.boolean_file", (char*)"io_test_ascii", (tmp$5)&_ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE13IO_TEST_ASCIIEv, (boolean)0 );
	label$5:;
}

__attribute__(( constructor )) static void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE20IO_TEST_UTF16LE_CTOREv( void )
{
	_unusedlabel: ; void *_llvmbug18658 = &&_unusedlabel;
	label$8:;
	_ZN4FBCU8ADD_TESTEPcS0_PFvvEb( (char*)"fbc_tests.boolean_.boolean_file", (char*)"io_test_utf16le", (tmp$5)&_ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE15IO_TEST_UTF16LEEv, (boolean)0 );
	label$9:;
}

__attribute__(( constructor )) static void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE19IO_TEST_BINARY_CTOREv( void )
{
	_unusedlabel: ; void *_llvmbug18658 = &&_unusedlabel;
	label$12:;
	_ZN4FBCU8ADD_TESTEPcS0_PFvvEb( (char*)"fbc_tests.boolean_.boolean_file", (char*)"io_test_binary", (tmp$5)&_ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE14IO_TEST_BINARYEv, (boolean)0 );
	label$13:;
}

__attribute__(( constructor )) static void _ZN5TESTS9FBC_TESTS8BOOLEAN_12BOOLEAN_FILE13SUITE_CTOR166Ev( void )
{
	_unusedlabel: ; void *_llvmbug18658 = &&_unusedlabel;
	label$14:;
	_ZN4FBCU9ADD_SUITEEPcPFivES2_( (char*)"fbc_tests.boolean_.boolean_file", (tmp$4)0u, (tmp$4)0u );
	label$15:;
}
