typedef   signed char       int8;
typedef unsigned char      uint8;
typedef   signed short      int16;
typedef unsigned short     uint16;
typedef   signed int        int32;
typedef unsigned int       uint32;
typedef   signed long long  int64;
typedef unsigned long long uint64;
typedef struct { char *data; int32 len; int32 size; } FBSTRING;
typedef int8 boolean;
int32 fb_FileOpen( const FBSTRING*, const uint32, const uint32, const uint32, const int32, const int32 );
int32 fb_FileClose( const int32 );
int32 fb_FileFree( void );
int32 fb_FileKill( const FBSTRING* );
void fb_PrintString( const int32, const FBSTRING*, const int32 );
FBSTRING* fb_StrInit( void*, const int32, const void*, const int32, const int32 );
FBSTRING* fb_StrAssign( void*, const int32, const void*, const int32, const int32 );
void fb_StrDelete( const FBSTRING* );
int32 fb_StrCompare( const void*, const int32, const void*, const int32 );
FBSTRING* fb_StrAllocTempDescZEx( const char*, const int32 );
FBSTRING* fb_StrLcase2( const FBSTRING*, const int32 );
FBSTRING* fb_CurDir( void );
FBSTRING* fb_DirNext( int32* );
FBSTRING* fb_Dir( const FBSTRING*, const int32, int32* );
int32 fb_RmDir( const FBSTRING* );
static void fb_ctor__dirzruntime( void ) __attribute__(( constructor ));
void DELETE_FILE_IF_PRESENT( FBSTRING* );
void CLEANUP_TREE( void );
void WRITE_TEXT_FILE( FBSTRING*, FBSTRING* );
